# Generated by Django 4.2.7 on 2025-01-15 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nourish_home', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
    ]
