# Generated by Django 4.2.7 on 2025-01-20 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nourish_home', '0004_recipe_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(related_name='recipes', through='nourish_home.RecipeCategory', to='nourish_home.category'),
        ),
        migrations.AlterField(
            model_name='recipecategory',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='nourish_home.category'),
        ),
    ]
