# Generated by Django 4.2.7 on 2025-01-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nourish_home', '0009_alter_recipe_categories_alter_recipe_featured_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipecategory',
            name='recipe',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='RecipeCategory',
        ),
    ]
